export const vehicles = [
  { id: 'plane', name: '飞机', icon: '✈️', cat: 'air' },
  { id: 'helicopter', name: '直升机', icon: '🚁', cat: 'air' },
  { id: 'rocket', name: '火箭', icon: '🚀', cat: 'air' },
  { id: 'ufo', name: '飞碟', icon: '🛸', cat: 'air' },
  { id: 'balloon', name: '热气球', icon: '🎈', cat: 'air' },
  { id: 'paraglider', name: '滑翔伞', icon: '🪂', cat: 'air' },
  { id: 'car', name: '汽车', icon: '🚗', cat: 'ground' },
  { id: 'taxi', name: '出租车', icon: '🚕', cat: 'ground' },
  { id: 'bus', name: '巴士', icon: '🚌', cat: 'ground' },
  { id: 'van', name: '面包车', icon: '🚐', cat: 'ground' },
  { id: 'motorcycle', name: '摩托车', icon: '🏍️', cat: 'ground' },
  { id: 'bike', name: '自行车', icon: '🚲', cat: 'ground' },
  { id: 'scooter', name: '滑板车', icon: '🛴', cat: 'ground' },
  { id: 'truck', name: '卡车', icon: '🚚', cat: 'ground' },
  { id: 'jeep', name: '吉普', icon: '🚙', cat: 'ground' },
  { id: 'ambulance', name: '救护车', icon: '🚑', cat: 'ground' },
  { id: 'firetruck', name: '消防车', icon: '🚒', cat: 'ground' },
  { id: 'police', name: '警车', icon: '🚓', cat: 'ground' },
  { id: 'tractor', name: '拖拉机', icon: '🚜', cat: 'ground' },
  { id: 'ship', name: '轮船', icon: '🚢', cat: 'water' },
  { id: 'boat', name: '帆船', icon: '⛵', cat: 'water' },
  { id: 'speedboat', name: '快艇', icon: '🚤', cat: 'water' },
  { id: 'cruise', name: '邮轮', icon: '🛳️', cat: 'water' },
  { id: 'canoe', name: '独木舟', icon: '🛶', cat: 'water' },
  { id: 'train', name: '火车', icon: '🚂', cat: 'rail' },
  { id: 'metro', name: '地铁', icon: '🚇', cat: 'rail' },
  { id: 'tram', name: '电车', icon: '🚊', cat: 'rail' },
  { id: 'bullet', name: '高铁', icon: '🚄', cat: 'rail' },
  { id: 'monorail', name: '单轨', icon: '🚝', cat: 'rail' },
  { id: 'lightrail', name: '轻轨', icon: '🚈', cat: 'rail' },
  { id: 'dragon', name: '飞龙', icon: '🐉', cat: 'fun' },
  { id: 'unicorn', name: '独角兽', icon: '🦄', cat: 'fun' },
  { id: 'sleigh', name: '雪橇', icon: '🛷', cat: 'fun' },
  { id: 'magic', name: '精灵', icon: '🧞', cat: 'fun' },
  { id: 'ghost', name: '幽灵', icon: '👻', cat: 'fun' },
  { id: 'alien', name: '外星人', icon: '👽', cat: 'fun' },
  { id: 'robot', name: '机器人', icon: '🤖', cat: 'fun' },
  { id: 'crown', name: '王冠', icon: '👑', cat: 'fun' },
];

export const vehicleTabs = [
  { key: 'all', label: '全部' },
  { key: 'air', label: '✈ 航空' },
  { key: 'ground', label: '🚗 地面' },
  { key: 'water', label: '🚢 水上' },
  { key: 'rail', label: '🚂 铁路' },
  { key: 'fun', label: '🐉 趣味' },
];
